export function zhTypstMsg(s) {
  if (!s) return s
  const TYPE_ZH = {
    content: '内容', string: '字符串', dictionary: '字典', location: '位置', label: '标签',
    array: '数组', function: '函数', color: '颜色', length: '长度', float: '浮点数',
    int: '整数', integer: '整数', bool: '布尔值', bytes: '字节', datetime: '日期时间',
    angle: '角度', ratio: '比例', fraction: '分数', none: '无', auto: '自动',
    number: '数字', alignment: '对齐方式', gradient: '渐变', path: '路径',
    'element': '元素', 'selector': '选择器', 'symbol': '符号', 'strokes': '描边',
    'dictionary': '字典', 'array': '数组', 'content': '内容', 'string': '字符串',
    comma: '逗号', semicolon: '分号', pattern: '模式', identifier: '标识符',
    expression: '表达式', delimiter: '定界符', body: '主体', value: '值',
    argument: '参数', arguments: '个参数', key: '键', word: '单词', block: '块',
    'line break': '换行', 'semicolon or line break': '分号或换行',
    'closing brace': '右花括号', 'closing bracket': '右方括号', 'closing paren': '右括号',
    'closing bracket ]': '右方括号 ]', 'closing paren )': '右括号 )',
    markup: '标记', number: '数字', 'type': '类型', 'expected': '期望'
  }
  const zhType = str => str.split(',').map(x => x.trim()).map(x => TYPE_ZH[x.toLowerCase()] || x).join('、')
  const fixes = [
    [/unexpected end of (file|input|content)/i, '意外的输入结尾'],
    [/unexpected\s+([^,\s]+)/i, (m, a) => '意外的' + zhType(a)],
    [/expected string, dictionary, location, or label, found content/i, '期望字符串、字典、位置或标签，但找到的是内容'],
    [/expected at least (\d+) arguments?/i, '期望至少 $1 个参数'],
    [/expected at most (\d+) arguments?/i, '期望至多 $1 个参数'],
    [/expected\s+(.+?),\s*found\s+([^,。\n]+)/i, (m, a, b) => '期望 ' + zhType(a) + '，但找到 ' + zhType(b)],
    [/expected\s+`([^`]+)`/i, (m, a) => '期望 `' + a + '`'],
    [/expected\s+(.+?)(?=,|\.|;|\n|$)/i, (m, a) => '期望 ' + zhType(a.trim())],
    [/too many arguments/i, '参数过多'],
    [/too few arguments/i, '参数过少'],
    [/missing argument/i, '缺少参数'],
    [/unknown variable:\s*/gi, '未知变量：'],
    [/unknown function:\s*/gi, '未知函数：'],
    [/undefined function:\s*/gi, '未定义的函数：'],
    [/cannot call non-function value/i, '不能调用非函数值'],
    [/cannot be called/i, '该值不可被调用'],
    [/unexpected argument/i, '意外的参数'],
    [/no field named/i, '没有名为该名称的字段'],
    [/field not found/i, '找不到该字段'],
    [/cannot access field/i, '无法访问字段'],
    [/dictionary does not contain key/i, '字典中不包含该键'],
    [/label name must not be empty/i, '标签名称不能为空'],
    [/module\s+`([^`]+)`\s+does not contain\s+`([^`]+)`/i, '模块 `$1` 中不包含 `$2`'],
    [/does not exist in the document/i, '在文档中不存在'],
    [/is not attached to anything/i, '未绑定到任何内容'],
    [/unclosed string/i, '未闭合的字符串'],
    [/unclosed block/i, '未闭合的代码块'],
    [/unclosed delimiter/i, '未闭合的定界符'],
    [/unexpected token/i, '意外的标记'],
    [/syntax error/i, '语法错误'],
    [/division by zero/i, '除以零'],
    [/cannot convert\s+([^ ]+)\s+to\s+([^ ,。\n]+)/i, (m, a, b) => '无法将 ' + a + ' 转换为 ' + b],
    [/not a valid\s+([a-z]+)/i, '不是有效的$1'],
    [/cycle detected/i, '检测到循环引用'],
    [/recursion limit/i, '递归次数达到上限'],
    [/no matching function/i, '没有匹配的函数'],
    [/argument count mismatch/i, '参数数量不匹配'],
    [/type mismatch/i, '类型不匹配'],
    [/cannot mix/i, '不能混用'],
    [/duplicate/i, '重复'],
    [/not allowed here/i, '此处不允许'],
    [/can only be used/i, '只能用于'],
    [/must be a ([a-z]+)/i, '必须是$1'],
    [/out of bounds/i, '超出范围'],
    [/module not found/i, '找不到模块'],
    [/unknown path/i, '未知路径'],
    [/permission denied/i, '没有权限'],
    [/failed to fetch/i, '无法获取'],
    [/404 not found/i, '404 找不到'],
    [/file not found/i, '找不到该文件'],
    [/\(searched at ([^)]+)\)/i, '（已搜索 $1）'],
    [/failed to load file/i, '无法读取文件'],
    [/access denied/i, '没有访问权限'],
    [/cannot read file outside of project root[^。\n]*/i, '无法读取项目根目录之外的路径（可通过 --root 参数调整项目根目录）'],
    [/the file could not be found/i, '找不到该文件'],
    [/cannot read file/i, '无法读取文件'],
    [/unknown field:\s*/gi, '未知字段：'],
    [/unresolved import/i, '无法解析的导入'],
    [/package not found/i, '找不到该包'],
    [/failed to download package/i, '包下载失败'],
    [/network (error|request) failed/i, '网络请求失败'],
    [/invalid utf-8/i, '文件不是有效的 UTF-8 编码'],
    [/unable to access the file/i, '无法访问该文件']
  ]
  for (const [re, zh] of fixes) s = s.replace(re, zh)
  return s
}
